panel: Check for currentApplet property before operating on it
Avoids spam to the following errors in logs:

    /usr/share/plasma/plasmoids/org.kde.panel/contents/ui/ConfigOverlay.qml:52:
    TypeError: Value is null and could not be converted to an object