[desktoppackage] Fix null check of containment
It was missing to check if containment exist or not before
trying to access it which causes errors like:
TypeError: Cannot read property 'containmentDisplayHints' of null