Fix build
Currently, plasma-desktop fails to build with the following error
message:

/data/projects/src/plasma-desktop/kcms/keys/globalaccelmodel.cpp:184:83: error: no viable conversion from 'QList<QKeySequence>' to 'const QList<int>'
                auto reply = m_globalAccelInterface->setForeignShortcut(actionId, keys);

given that Plasma requires KF 5.90 or newer, the ifdef can be removed.